# Generated by Django 5.1.4 on 2025-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default='#', max_length=250, null=True),
        ),
    ]
